### ISSUE TITLE
Feedback from peer review

### ISSUE THREAD

**Issue by everittB** [UBC-MDS/DSCI-522_Bank-Marketing#26]
- Add EDA into the report
- pdays, make categorical (have they been contacted before or not)
- Summarize our findings, things we would different (with more time)
- Deal with the difference in sample size (between signing up and not signing up)
- Cross validation graph - should show the training score vs test score 
- Switch from pdf to github md version
- it is suggested that we should not exclude the duration attribute because it is still important to see the history of the call duration for each customer

**Comment by everittB** [comment]
- Made pdays a categorical variable, True if a customer had been contact before and false otherwise
- Updated the final report to provide more details of the steps we took
- Update the 'class_wight' attribute in the DecisionTreeClassifier to deal with the unbalance sample size in each class
- Cross-validation graph shows the average test accuracy for each depth, no need to change
- Changed output of final document to github_document
- Provided reasoning in the report as to why duration was dropped from the analysis

**Comment by sabrinatkk** [comment]
- Added EDA into the final report

https://github.com/UBC-MDS/DSCI-522_Bank-Marketing/commit/cac3e7b06a209930cff32c02206963667f0104f2
