### ISSUE TITLE
Remove unnecessary info from README

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI-522_Bank-Marketing#39]
At this point in the project the plan and presentation sections are not really needed, so you can delete them or move them to a file called proposal.md.

**Comment by sabrinatkk** [comment]
Thank you ! Recommendation has been accepted and reflected on the latest readme.

https://github.com/UBC-MDS/DSCI-522_Bank-Marketing/pull/44/commits/a78855bdc883eaec04659f45be8eb6f603b149ac
