### ISSUE TITLE
Improve usage instructions

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI-522_Bank-Marketing#40]
Improve usage instructions by suggesting the user:
-  clone/download the repo
- navigate to the root of the downloaded/cloned project using the command line
- run `make all`

**Comment by sabrinatkk** [comment]
Thanks @ttimbers . We have updated the readme page to reflect your recommendation!

https://github.com/UBC-MDS/DSCI-522_Bank-Marketing/pull/44/commits/a78855bdc883eaec04659f45be8eb6f603b149ac
