### ISSUE TITLE
Final report should not have lines crossed out.

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI-522_Bank-Marketing#42]
In the data section there are several sections where the lines are crossed out. This should not be done in a final report.

**Comment by sabrinatkk** [comment]
Thanks @ttimbers for your recommendation. Our final report has been updated to reflect the changes.

https://github.com/UBC-MDS/DSCI-522_Bank-Marketing/pull/44/commits/20eed3ee411e38a6f8c5a8010c258b93de85d91e
