### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by eric-f** [UBC-MDS/DSCI-522_Bank-Marketing#7]
__Mechanics__

* @sabrinatkk, in your proposal repos, need to have a link to the project repo in addition to the link to v1.0.

* Also, the current link to v1.0 points to the release page, you might create a direct link v1.0 of the repo with https://github.com/UBC-MDS/DSCI-522_Bank-Marketing/tree/v1.0. 

* Might want to replace the standard repo name at the top of README in the project repo with a proper project title in a natural language, say 'Bank Marketing'.

* For directory structure, you might want to have two folders, one for intermediate outputs and another for final reports or executive summaries. Right now there is only a folder called results/, presumably for intermediate outputs. You might want to create a doc/ folder for the deliverables.

__Reasoning__

* Should have elaborated on how you are going to build your decision tree, e.g. what predictors to consider, how to prune the tree, validation/cross-validation, etc. 

* Also, while the primary function of a decision tree is to predict successful sign-up or not (output) given a set of customer characteristics (inputs), you might want to explain how you are going to tackle the 'inverse problem' of identifying the group of clients (set of inputs) with high conversion probability. Okay, with a single tree I guess you can list all the 'successful' nodes, but maybe there are more interesting presentations? 

* Presentation section needs to be more specific. For example, how are you going to visualize the fitted tree? Depending on the number of predictors and the depth of the tree, it might be overwhelming to plot the entire tree. Also, what are you going to include in the summary table of selected features? I guess you can rank them by predictive power or importance. Can you think of any other useful summaries?

**Comment by sabrinatkk** [comment]
@eric-f Thank you for the reminder. 

I have addressed Mechanics point 1 and 2. 

We will provide updates on readme.md to respond to the rest of your recommendation.

**Comment by everittB** [comment]
Updated the README to be more specific on our plan for building the decision tree classifier, the primary objective of our classifier, and the results we will present at the end of our analysis. #9 #8
